[server]
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[browser]
serverPort = "8501"
gatherUsageStats = false

[theme]
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"
